# Generated by Django 2.0 on 2020-02-17 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServeOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='服务区域')),
                ('work_name', models.CharField(max_length=50, verbose_name='服务机构名')),
                ('name', models.CharField(max_length=50, verbose_name='服务对象')),
                ('mobile', models.CharField(max_length=11, verbose_name='电话号码')),
                ('user_id', models.IntegerField(default=0, verbose_name='工单编号')),
                ('satis_type', models.IntegerField(choices=[(1, '满意'), (2, '一般'), (3, '不满意')], default=0, verbose_name='服务满意度')),
                ('work_type', models.IntegerField(choices=[(1, '已审核'), (2, '审核中'), (3, '未审核')], default=0, verbose_name='工单状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='回访时间')),
                ('worker_name', models.CharField(max_length=50, verbose_name='服务人员姓名')),
                ('worker_type', models.IntegerField(choices=[(1, '社工'), (2, '志愿者'), (3, '服务公司人员'), (4, '服务中心人员')], default=0, verbose_name='服务人员类别')),
            ],
            options={
                'verbose_name': '服务组织',
                'verbose_name_plural': '服务组织',
            },
        ),
        migrations.CreateModel(
            name='ServerOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_s', models.CharField(max_length=100, verbose_name='服务区域')),
                ('work_name', models.CharField(max_length=50, verbose_name='服务机构名')),
                ('name', models.CharField(max_length=50, verbose_name='服务对象')),
                ('mobile', models.CharField(max_length=11, verbose_name='电话号码')),
                ('user_id', models.IntegerField(default=0, verbose_name='工单编号')),
                ('satis_type', models.IntegerField(choices=[(1, '满意'), (2, '一般'), (3, '不满意')], default=0, verbose_name='服务满意度')),
                ('work_type', models.IntegerField(choices=[(1, '已审核'), (2, '审核中'), (3, '未审核')], default=0, verbose_name='工单状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='回访时间')),
                ('worker_name', models.CharField(max_length=50, verbose_name='服务人员姓名')),
                ('worker_type', models.IntegerField(choices=[(1, '社工'), (2, '志愿者'), (3, '服务公司人员'), (4, '服务中心人员')], default=0, verbose_name='服务人员类别')),
            ],
            options={
                'verbose_name': '服务人员',
                'verbose_name_plural': '服务人员',
            },
        ),
        migrations.CreateModel(
            name='TuodiUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='老人姓名')),
                ('address', models.CharField(max_length=100, verbose_name='老人现居住地归属地')),
                ('user_birth', models.DateField(verbose_name='出生日期')),
                ('id_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('mobile', models.CharField(max_length=11, verbose_name='老人联系电话')),
                ('mobile_r', models.CharField(max_length=11, verbose_name='家属联系电话')),
                ('user_id', models.IntegerField(default=0, verbose_name='老人卡号')),
                ('worker_name', models.CharField(max_length=50, verbose_name='创建人')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建日期')),
                ('work_type', models.IntegerField(choices=[(1, '已审核'), (2, '审核中'), (3, '未审核')], default=0, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '托底人员',
                'verbose_name_plural': '托底人员',
            },
        ),
        migrations.CreateModel(
            name='ZifeiUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_z', models.CharField(max_length=50, verbose_name='老人姓名')),
                ('address', models.CharField(max_length=100, verbose_name='老人现居住地归属地')),
                ('user_birth', models.DateField(verbose_name='出生日期')),
                ('id_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('mobile', models.CharField(max_length=11, verbose_name='老人联系电话')),
                ('mobile_r', models.CharField(max_length=11, verbose_name='家属联系电话')),
                ('user_id', models.IntegerField(default=0, verbose_name='老人卡号')),
                ('worker_name', models.CharField(max_length=50, verbose_name='创建人')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建日期')),
                ('work_type', models.IntegerField(choices=[(1, '已审核'), (2, '审核中'), (3, '未审核')], default=0, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '自费人员',
                'verbose_name_plural': '自费人员',
            },
        ),
    ]
