# Generated by Django 2.0 on 2020-02-17 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='城市')),
                ('desc', models.CharField(max_length=300, verbose_name='机构描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市管理',
                'verbose_name_plural': '城市管理',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.IntegerField(choices=[(1, '自费'), (2, '政府补助')], default=0, verbose_name='付费方式')),
                ('change_price', models.IntegerField(choices=[(1, '允许'), (2, '不允许')], default=0, verbose_name='是否允许公司自行修改价格')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '收费类型管理',
                'verbose_name_plural': '收费类型管理',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('1', '社会组织'), ('2', '志愿者组织'), ('3', '居家养老服务中心'), ('4', '社区居委会'), ('5', '养老机构'), ('6', '加盟企业')], max_length=100, verbose_name='机构类型')),
                ('work_name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('desc', models.CharField(max_length=300, verbose_name='机构描述')),
                ('address', models.CharField(max_length=100, verbose_name='办公地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='覆盖人数')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='封面')),
                ('audit_status', models.IntegerField(choices=[(1, '已审核'), (2, '审核中'), (3, '未审核')], default=0, verbose_name='审核状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '服务机构管理',
                'verbose_name_plural': '服务机构管理',
            },
        ),
        migrations.CreateModel(
            name='Service_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50, verbose_name='服务人员姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_company', models.CharField(max_length=50, verbose_name='就职公司')),
                ('work_position', models.CharField(max_length=50, verbose_name='公司职位')),
                ('points', models.CharField(max_length=50, verbose_name='工作特点')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='负责人数')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Service', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '服务人员管理',
                'verbose_name_plural': '服务人员管理',
            },
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='操作员')),
                ('work_name', models.CharField(max_length=50, verbose_name='服务机构')),
                ('worker_name', models.CharField(max_length=50, verbose_name='服务人员')),
                ('name', models.CharField(max_length=50, verbose_name='服务对象')),
                ('comments', models.CharField(max_length=200, verbose_name='反馈')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
            },
        ),
    ]
