# Generated by Django 2.0 on 2020-02-17 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='报表名称')),
                ('url', models.URLField(verbose_name='报表地址')),
                ('start', models.CharField(choices=[(1, '是'), (2, '否')], max_length=150, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '报表管理',
                'verbose_name_plural': '报表管理',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='服务区域')),
                ('name', models.CharField(max_length=50, verbose_name='服务对象')),
                ('deductions', models.CharField(choices=[(1, '是'), (2, '否')], max_length=150, verbose_name='是否扣款')),
                ('user_id', models.IntegerField(default=0, verbose_name='工单编号')),
                ('ticket_status', models.IntegerField(choices=[(1, '服务机构未接单'), (2, '服务机构已接单'), (3, '服务机构退单'), (4, '服务人员未接单'), (5, '服务人员已接单'), (6, '服务人员退单'), (7, '作废'), (8, '草稿')], default=0, verbose_name='工单状态')),
                ('work_name', models.CharField(max_length=50, verbose_name='服务机构')),
                ('worker_name', models.CharField(max_length=50, verbose_name='服务人员')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='工单创建时间')),
                ('return_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='回访时间')),
            ],
            options={
                'verbose_name': '工单明细统计',
                'verbose_name_plural': '工单明细统计',
            },
        ),
    ]
