# Generated by Django 2.0 on 2020-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a', models.CharField(max_length=10)),
                ('value_b', models.FloatField(max_length=10)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
